# Generated by Django 4.2 on 2023-06-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_conforder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'birthday'), (2, 'Wedding'), (3, 'Live music')], verbose_name='Category'),
        ),
    ]
